### ISSUE TITLE
Pickle the model

### ISSUE THREAD

**Issue by ikrambennasrbennasr** [OdysseasKr/neural-disaggregator#14]
Hi  @OdysseasKr , 
To pickle the model, should I pickle the all disaggregator? Thanks

**Comment by OdysseasKr** [comment]
I haven't tried to use pickle with the disaggregators so I don't know how well it would work. I don't see any reason why it shouldn't work like this.

Keep in mind that the ```model``` parameter of the disaggregator is a Keras ```Sequential``` object.

**Comment by OdysseasKr** [comment]
I guess that only the ```model``` attribute of the disaggregator is required for the deployment with Sagemaker. I haven't tried it myself though so don't take my word for it. 

If you manage to get it working let me know so that we can possible add the functionality. Or you can submit a pull request yourself.
