### ISSUE TITLE
Calling diaggregate with a single monthly aggregate reading.

### ISSUE THREAD

**Issue by cathreya** [OdysseasKr/neural-disaggregator#17]
This is probably more of an NILMTK question, but the disaggregate function in the `shortseq2pointdisaggregator.py` takes an Elecmeter object as a parameter. However, I am interested in getting the disaggregation of a single monthly aggregate. I tried to circumvent this by using something similar to the dataset converter code, by writing and reading from a hdf5 store, but I didn't manage to get anywhere with it. Is there any other way to achieve this?

**Comment by OdysseasKr** [comment]
Hi @cathreya! What do you mean by single monthly aggregate? Does this mean one value per month? Maybe you could use the ```sample_period``` attribute from NILMTK?

**Comment by cathreya** [comment]
Thanks for your reply! Instead of using values from the dataset, we want to to take total mains electricity usage per month from a user, and convert it to an Elecmeter input to the model.

**Comment by OdysseasKr** [comment]
In this case I am afraid that you have to write your own custom disaggregator. All models in this repo are designed to work with fast sampling rates (usually with a sampling period of 6 seconds).

**Comment by cathreya** [comment]
Suppose we had 6 seconds aggregates from the user, would we be able to create Elecmeter objects for those?

**Comment by OdysseasKr** [comment]
Aah ok I see. So you want to use a feed of user data but not a dataset? NILMTK is a toolkit for working with datasets so, since you couldn't figure out the converter, you can not use neural-disaggregator.

**Comment by cathreya** [comment]
That is a shame. Thank you for your help and your time.
