### ISSUE TITLE
Big different results with your post when I run your code from RNN 

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/neural-disaggregator#20]
Hi, I have no idea why so big different results when I run exactly the same code you posted. 

![0FB$_KD~9BLZO6%YR$A$@V5](https://user-images.githubusercontent.com/25447481/66657277-256f7880-ec72-11e9-8618-2642a1f3af08.png)

**Comment by Hessen525** [comment]
![3}QV_)@KN1QOVS%${AB8CUR](https://user-images.githubusercontent.com/25447481/66658145-73d14700-ec73-11e9-90b2-72b6796e7734.png)
Thanks!

**Comment by OdysseasKr** [comment]
Hi @Hessen525 :) 

I don't have your results so I can not check myself but, looking at your plot I have some points:
1. Your plot doesn't look all that bad in terms of events. That means that (from what I can see) the spikes match even if the amount of watts is not correct.
2. Please check the on_power_threshold in the metadata of NILMTK. Sometimes it happens that the threshold is too high, and thus, even if the network predicts highers wattage, it's still not that high for the device to be considered on. Hence, the metrics are worse.
3. Judging from the plot, it seems like we are not testing on the same data or the plotting behaves differently.

**Comment by Hessen525** [comment]
Hi, @OdysseasKr :

I used REDD low-frequency Dataset from http://redd.csail.mit.edu/, is that the same as yours?
Thank you so much for your reply and help!

**Comment by OdysseasKr** [comment]
Yes that is the same indeed.

**Comment by Hessen525** [comment]
> Yes that is the same indeed.

Could you give me more details about how to fix it?  ex: where I can check the on_power_threshold in the metadata of NILMTK?

Thanks!

**Comment by Hessen525** [comment]
> Yes that is the same indeed.

After I increased epochs from 5 to 11, the results are very close to yours. 
![`{0OP@G~JV77K(H3E(PW@ZG](https://user-images.githubusercontent.com/25447481/66827367-29a4da00-ef81-11e9-87b0-90a8ab8976b5.png)

**Comment by OdysseasKr** [comment]
Glad it worked out! The results are very similar.

For future reference, in order to access the nilmtk metadata, you need to find the files of [this](https://github.com/nilmtk/nilm_metadata) package which is installed automatically when you install nilmtk.

**Comment by RengarWang** [comment]
> Hi, I have no idea why so big different results when I run exactly the same code you posted.
> 
> ![0FB$_KD~9BLZO6%YR$A$@V5](https://user-images.githubusercontent.com/25447481/66657277-256f7880-ec72-11e9-8618-2642a1f3af08.png)

I had the same problem
my result is
============ Recall: 0.06080812748658777
============ Precision: 0.7873688147161255
============ Accuracy: 0.29049305213046556
============ F1 Score: 0.11289725264136873
============ Relative error in total energy: 0.7858544224150322
============ Mean absolute error(in Watts): 19.859596349905722

i try epochs =15 , maybe it is better.

**Comment by RengarWang** [comment]
> > Hi, I have no idea why so big different results when I run exactly the same code you posted.
> > ![0FB$_KD~9BLZO6%YR$A$@V5](https://user-images.githubusercontent.com/25447481/66657277-256f7880-ec72-11e9-8618-2642a1f3af08.png)
> 
> I had the same problem
> my result is
> ============ Recall: 0.06080812748658777
> ============ Precision: 0.7873688147161255
> ============ Accuracy: 0.29049305213046556
> ============ F1 Score: 0.11289725264136873
> ============ Relative error in total energy: 0.7858544224150322
> ============ Mean absolute error(in Watts): 19.859596349905722
> 
> i try epochs =15 , maybe it is better.

i got the result on epochs = 15 , but it is not good.
![1602032821(1)](https://user-images.githubusercontent.com/51586022/95275972-85e0c800-087c-11eb-8878-ba62dece07de.png)
