### ISSUE TITLE
How do you extract activations and select windows in your code?

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/neural-disaggregator#22]
Hi, @OdysseasKr 
How do you extract activations and select window width in your code as written in Neural NILM?
1.  extract activations 
![F}6O`JEH)7EE61BDUY7H335](https://user-images.githubusercontent.com/25447481/67021116-c1e1c100-f131-11e9-93c1-9a7c8b3a74c2.png)
2. select window width
![KZWED8S2QV`9P%5%L1KESH0](https://user-images.githubusercontent.com/25447481/67023186-f4d98400-f134-11e9-8ff9-d5e33122fbf8.png)

THANKS!

**Comment by OdysseasKr** [comment]
Hi @Hessen525. This code is based on the architectures of Neural NILM but uses the raw timeseries of the dataset. So there is no data augmentation and the window size is picked by the experimentor.

This repo is meant act as a boilerplate for your own experiments so I can not make suggestions in terms of data extraction, windows etc.

**Comment by Hessen525** [comment]
> Hi @Hessen525. This code is based on the architectures of Neural NILM but uses the raw timeseries of the dataset. So there is no data augmentation and the window size is picked by the experimentor.
> 
> This repo is meant act as a boilerplate for your own experiments so I can not make suggestions in terms of data extraction, windows etc.

All right!Thanks!
I have another question about mains.good_sections() in your code. 
Does it split the whole  test_elec.mains().all_meters()[0]  into several sections automatically?

**Comment by OdysseasKr** [comment]
According to NILMTK documentation

> sections : list of TimeFrame objects
> Each good section in df is marked with a TimeFrame. If this df ends with an open-ended good section (assessed by examining look_ahead) then the last TimeFrame will have end=None. If this df starts with an open-ended good section then the first TimeFrame will have start=None.

For NILMTK-related code it's better to refer to their documentation.
