### ISSUE TITLE
 train_across_buildings and train_across_buildings_chunk

### ISSUE THREAD

**Issue by HouKun-github** [OdysseasKr/neural-disaggregator#25]
Hi, first of all, thank you for your work. I have a question that I do n’t quite understand. I hope to get your answers. What is the use of 'train_across_buildings_chunk'? I do n’t know what this training is different from the previous 'train on chunk' It seems that 'train_across_buildings_chunk' is not used in the program. What is the purpose of this code?

**Comment by OdysseasKr** [comment]
Hello,
Every disaggregator has two methods ```train``` and ```train_across_buildings```. The first one trains using one meter while the second receives an array of meters. Each of these methods use the ```train_on_chunk``` and the ```train_across_buildings_chunk```. They separate a chunk of the data and train the model. 

Basically the only difference is that ```train_across_buildings_chunk``` supports chunks from multiple buildings.

**Comment by hk123456789Q** [comment]
> 
> 
> Hello,
> Every disaggregator has two methods `train` and `train_across_buildings`. The first one trains using one meter while the second receives an array of meters. Each of these methods use the `train_on_chunk` and the `train_across_buildings_chunk`. They separate a chunk of the data and train the model.
> 
> Basically the only difference is that `train_across_buildings_chunk` supports chunks from multiple buildings.

Thank you for your answer, I will try to train with the data of the series table to evaluate the performance of both ways.

**Comment by hk123456789Q** [comment]
> 
> 
> > Hello,
> > Every disaggregator has two methods `train` and `train_across_buildings`. The first one trains using one meter while the second receives an array of meters. Each of these methods use the `train_on_chunk` and the `train_across_buildings_chunk`. They separate a chunk of the data and train the model.
> > Basically the only difference is that `train_across_buildings_chunk` supports chunks from multiple buildings.
> 
> Thank you for your answer, I will try to train with the data of the series table to evaluate the performance of both ways.
Hello, sorry to bother you, if I want to use a series of tables for training, how can I modify the code on the original code, does the "nilmtk" toolkit provide training data using some table data, I don't seem to find it. Hope to get your help, thank you.

**Comment by OdysseasKr** [comment]
> > Hello,
> > Every disaggregator has two methods `train` and `train_across_buildings`. The first one trains using one meter while the second receives an array of meters. Each of these methods use the `train_on_chunk` and the `train_across_buildings_chunk`. They separate a chunk of the data and train the model.
> > Basically the only difference is that `train_across_buildings_chunk` supports chunks from multiple buildings.
> 
> Thank you for your answer, I will try to train with the data of the series table to evaluate the performance of both ways.

Please note that you are not supposed to call the `train_on_chunk` and `train_across_buildings_chunk` directly. Instead use the methods `train` and `train_across_buildings`.
