### ISSUE TITLE
Why just load mains from only one meter of site_meter?

### ISSUE THREAD

**Issue by Hessen525** [OdysseasKr/neural-disaggregator#26]
Thanks for your awesome work, but I have a question about it. It looks like you just load
only one meter of site meter, as shown in your code: 
train_mains = train_elec.mains().all_meters()[0] # The aggregated meter that provides the input

but there are two meters for recording site meter. 
The aggregate powers summed together by elec.mains().power_series_all_data().

**Comment by Hessen525** [comment]
@OdysseasKr

**Comment by OdysseasKr** [comment]
Hi Hessen. The REDD dataset has two aggregated meters. Each one of them corresponds to a subset of the appliances for each house. The particular device is aggregated in the first mains meter and for this reason we only use this one. 

Does this answer your question?

**Comment by Hessen525** [comment]
Sorry for the late reply. I get right now, thanks for your help!
