### ISSUE TITLE
'GRUDisaggregator' object has no attribute '_pre_disaggregation_checks

### ISSUE THREAD

**Issue by Leodenbeing** [OdysseasKr/neural-disaggregator#27]
I can not find this method in your code

**Comment by dahurtados** [comment]
I have the same problem but in DAE disaggregator.
'DAEDisaggregator' object has no attribute '_pre_disaggregation_checks'

**Comment by Leodenbeing** [comment]
This problem in all disaggregator, hadn’t your found that?




| |
13026316095
|
|
邮箱：13026316095@163.com
|

Signature is customized by Netease Mail Master

On 12/12/2019 22:03, dahurtados wrote:

I have the same problem but in DAE disaggregator.
'DAEDisaggregator' object has no attribute '_pre_disaggregation_checks'

**Comment by dahurtados** [comment]
I can't find anything, if you find something or find something, I'll let you know or let me know.

**Comment by Leodenbeing** [comment]
Can u run GRUExample.ipynb without problems?




| |
13026316095
|
|
邮箱：13026316095@163.com
|

Signature is customized by Netease Mail Master

On 12/12/2019 22:24, dahurtados wrote:

I can't find anything, if you find something or find something, I'll let you know or let me know.

**Comment by Leodenbeing** [comment]
My wechat is Imp561609351, if u are interested in searching nilm, we can discuss it




| |
13026316095
|
|
邮箱：13026316095@163.com
|

Signature is customized by Netease Mail Master

On 12/12/2019 22:29, Leodenbeing wrote:
Can u run GRUExample.ipynb without problems?




| |
13026316095
|
|
邮箱：13026316095@163.com
|

Signature is customized by Netease Mail Master

On 12/12/2019 22:24, dahurtados wrote:

I can't find anything, if you find something or find something, I'll let you know or let me know.

**Comment by OdysseasKr** [comment]
This problem has been happening a lot lately. NILMTK was updated to version 0.3 which breaks this repo, They defined a new Disaggregator class which is incompatible to the previous implementation.

You can either wait until there is a fix for this or follow Christofer's response here #21

**Comment by Leodenbeing** [comment]
Thank u so much, I will try that

At 2019-12-13 00:53:46, "Odysseas (Ody) Krystalakos" <notifications@github.com> wrote:


This problem has been happening a lot lately. NILMTK was updated to version 0.3 which breaks this repo, They defined a new Disaggregator class which is incompatible to the previous implementation.

You can either wait until there is a fix for this or follow Christofer's response here #21

**Comment by Leodenbeing** [comment]
This code can run without problem, I am so appreciate for your help! Thank u so much one more time!





At 2019-12-13 00:53:46, "Odysseas (Ody) Krystalakos" <notifications@github.com> wrote:


This problem has been happening a lot lately. NILMTK was updated to version 0.3 which breaks this repo, They defined a new Disaggregator class which is incompatible to the previous implementation.

You can either wait until there is a fix for this or follow Christofer's response here #21
