### ISSUE TITLE
How did you ues NILMTK

### ISSUE THREAD

**Issue by Merelynn** [OdysseasKr/neural-disaggregator#32]
Hi,there! I'm wondering how to get activations like the paper you sited in the "ReadME.txt", I download your code but I can't find where did you use NILMTK to get activations of the target electrical equipment. Hope to get an answer of how to use NILMTK to solve this problem.
Meanwhile, the title of your project is neural-disaggregator, but the coda is for predicting. I'm wondering the contact between them.
Thx for your answering!

**Comment by OdysseasKr** [comment]
Hi! I am not sure I fully understand your question but I will do my best to answer some points.
1. I believe you refer to Neural NILM, right?
2. NILMTK is used to get data from datasets and some utility operations. This code uses NILMTK to train models which are then used for disaggregation.
3. The models in this repository are used for energy disaggregation. This means that given the mains consumption as input, they output the consumption of a specific appliance. Therefore, we don't get activations, but the whole timeseries of the consumption for the target device. If you need only the activations, you need to get the points where the consumption is greater than the "turn on threshold". NILMTK provides thresholds for all appliances in REDD and UKDALE.
4. "Predict" in the context of Keras (and machine learning in general) is used when talking about getting results from new data. So we "train" or "fit" during the training phase and we "predict" during the deployment or testing phase. So "predicting" and "disaggregating" mean the same in this context.

**Comment by Merelynn** [comment]
Thanks a lot, your answer really helps me!
