### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by Yitao-jin** [OdysseasKr/neural-disaggregator#39]
Hi there,

We are a class group of graduate students at USC. We are interested in this project and want to import it to implement energy disaggregation. 
According to the official document and class requirement, MIT licence should be inlcuded.
Could you kindly add this license, which also makes the project more official?

Here is the reference
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository

**Comment by OdysseasKr** [comment]
That's actually a good idea. Added.
